In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]]) # define first array of shape (2,4)
arr2 = np.array([[5,6,7,8], [5,6,7,8]]) # define second array of shape (2,4)

print('arr1:', arr1)
print('\n arr2:', arr2)

arr1: [[1 2 3 4]
 [1 2 3 4]]

 arr2: [[5 6 7 8]
 [5 6 7 8]]


### ```np.concatenate((a, b), axis=0)```

In [4]:
# concat along the rows (axis=0)
cat = np.concatenate((arr1, arr2), axis=0)        # shape (4,4)

print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
# concat along the column (axis=1)
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 

In [6]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```


In [8]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [10]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(6,6)
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472 0.52667564]
 [0.90755375 0.8840703  0.08926896 0.5173446  0.34362129 0.21229369]
 [0.36067344 0.27077517 0.76162502 0.4780419  0.09899468 0.27539478]
 [0.79442731 0.51397031 0.45329481 0.25515125 0.1139766  0.82431305]
 [0.3177535  0.15230703 0.21497959 0.91211032 0.04311515 0.37595241]
 [0.31796557 0.35403302 0.93335757 0.3885452  0.89593944 0.14550322]]


In [ ]:
# split the array vertically into n evenly spaced chunks
varr1, varr2 = np.vsplit(arr, 2) # split into 2 arrays
print('varr1:\n', varr1)
print('\nvarr2:\n', varr2)

arr1:
 [[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472 0.52667564]
 [0.90755375 0.8840703  0.08926896 0.5173446  0.34362129 0.21229369]
 [0.36067344 0.27077517 0.76162502 0.4780419  0.09899468 0.27539478]]

arr2:
 [[0.79442731 0.51397031 0.45329481 0.25515125 0.1139766  0.82431305]
 [0.3177535  0.15230703 0.21497959 0.91211032 0.04311515 0.37595241]
 [0.31796557 0.35403302 0.93335757 0.3885452  0.89593944 0.14550322]]


In [ ]:
# split the array horizontally into n evenly spaced chunks
harr1, harr2 = np.hsplit(arr, 2) # split into 2 arrays
print('harr1:\n', harr1)
print('\nharr2:\n', harr2)

harr1:
 [[0.88594794 0.07791236 0.97964616]
 [0.90755375 0.8840703  0.08926896]
 [0.36067344 0.27077517 0.76162502]
 [0.79442731 0.51397031 0.45329481]
 [0.3177535  0.15230703 0.21497959]
 [0.31796557 0.35403302 0.93335757]]

harr2:
 [[0.24767146 0.75288472 0.52667564]
 [0.5173446  0.34362129 0.21229369]
 [0.4780419  0.09899468 0.27539478]
 [0.25515125 0.1139766  0.82431305]
 [0.91211032 0.04311515 0.37595241]
 [0.3885452  0.89593944 0.14550322]]
