In [1]:
import numpy as np

This notebook demonstrates various NumPy array slicing and indexing techniques, including basic indexing, slicing, boolean indexing, fancy indexing, and conditional selection.

In [4]:
# Create a 10x10 array with values from 0 to 99
arr = np.array(range(100)) # Create a numpy array with values from 0 to 99
print(arr)
arr1 = arr.reshape((10,10)) # Reshape the array to 10x10
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [5]:
# Create a 10x10 array with values from 0 to 99
arr = np.array(range(90)) # Create a numpy array with values from 0 to 99
print(arr)
arr1 = arr.reshape((10,10)) # Reshape the array to 10x10
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


ValueError: cannot reshape array of size 90 into shape (10,10)

### select an element by row and column indices

In [7]:
arr = np.array(range(100)).reshape((10,10)) # Create a 10x10 array with values from 0 to 99
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
# Select the element at row 5, column 5 using nested list-style indexing
print(arr[5][5]) #try selecting different indices
# Or more concisely using comma-separated indices
print(arr[5,5])

55
55


### indexing with slicing

In [9]:
# Slice the array: rows 1 to 3 (exclusive), columns 4 to 6 (exclusive)
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [17]:
# Create a 4D array (2x2x2x2) and use ellipsis to slice the first dimension
arr = np.array(range(16))
print("arr: ", arr)

arr = arr.reshape(2,2,2,2)
print("reshaped arr: ", arr)

# Equivalent to arr[0,:,:,:]
print("arr[0, ...]: ", arr[0, ...])
print("arr[0,:,:,:]: ", arr[0,:,:,:]) #both give the same result, this one is used more often

arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
reshaped arr:  [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
arr[0, ...]:  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
arr[0,:,:,:]:  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### assign a scalar to a slice by broadcasting

In [ ]:
arr = np.array(range(100)).reshape((10,10)) # Create a 10x10 array with values from 0 to 99
arr[1:3,:] = 100    # set rows 1 and 2 to 100
arr[:,8:] = 100 # set last two columns to 100, all the rows
print(arr)

[[  0   1   2   3   4   5   6   7 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37 100 100]
 [ 40  41  42  43  44  45  46  47 100 100]
 [ 50  51  52  53  54  55  56  57 100 100]
 [ 60  61  62  63  64  65  66  67 100 100]
 [ 70  71  72  73  74  75  76  77 100 100]
 [ 80  81  82  83  84  85  86  87 100 100]
 [ 90  91  92  93  94  95  96  97 100 100]]


### boolean indexing

In [20]:
arr1 = np.arange(25).reshape((5,5)) # 5x5 array
bools = np.array([True, True, False, True, False]) # boolean index array
print(arr1)
print("Boolean Indexing Result:")
print(arr1[bools])
print(arr1[bools].shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Boolean Indexing Result:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]
(3, 5)


In [21]:
print(arr1)
print("Boolean Negate Indexing Result:")
# negate the condition
print(arr1[~bools])    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Boolean Negate Indexing Result:
[[10 11 12 13 14]
 [20 21 22 23 24]]


In [22]:
arr2 = np.array([1,2,3,4,5]) # sample array for condition-based indexing
# multiple conditions
print(arr2<2) # print boolean array where condition is met
print(arr2>4) # print boolean array where condition is met
print(arr1[(arr2<2) | (arr2>4)])    # select rows in arr1 where arr2 < 2 or arr2 > 4

[ True False False False False]
[False False False False  True]
[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [26]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(5,5)
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]


In [ ]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])        #this selects specific elements based on the provided row and column indices

[0.79442731 0.8840703  0.21229369]


### dimension inference

In [29]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)) # 1D array with values from 0 to 15
print(arr)
print(arr.shape)
print(" ")
arr = arr.reshape((4,-1)) # reshape to 4 rows and infer columns
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)


### find elements/indices by conditions

In [ ]:
arr = np.arange(16).reshape(4,4) # 4x4 array
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [31]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [32]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10)) # if element > 5 return -1 else return 10

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [33]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


Next [Module](./8.%20Manipulate%20an%20Array.ipynb)