In [1]:
import numpy as np

### select the unique elements from an array

In [2]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr)) # get unique values

[1 2 3 4 5 6]


In [3]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True) # get unique values and their counts
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


### compute the intersection & union of two arrays

| Feature | `np.union1d(ar1, ar2)` | `np.intersect1d(ar1, ar2)` |
| :--- | :--- | :--- |
| **Mathematical Concept** | **Set Union** ($\cup$) | **Set Intersection** ($\cap$) |
| **Result Definition** | All **unique** elements present in **either** `ar1` **or** `ar2`. | Only the elements present in **both** `ar1` **and** `ar2`. |
| **Element Uniqueness** | The output array is guaranteed to contain only **unique** values. | The output array is guaranteed to contain only **unique** values. |
| **Ordering** | The output is always returned as a **sorted** 1-D array. | The output is always returned as a **sorted** 1-D array. |
| **Array Dimension** | Both functions coerce the input arrays to **1-D** before computation. | Both functions coerce the input arrays to **1-D** before computation. |
| **Example (A = [1, 2, 3], B = [3, 4, 5])** | `[1, 2, 3, 4, 5]` | `[3]` |

In [4]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [ ]:
# intersection
print(np.intersect1d(arr1, arr2)) # get the common values

[3 4 5]


In [ ]:
# union
print(np.union1d(arr1, arr2)) # get all unique values from both arrays

[1 2 3 4 5 6 7]


### compute whether each element of an array is contained in another

In [ ]:
print(np.isin(arr1, arr2)) # check which elements of arr1 are in arr2

[False False  True  True  True]


### compute the elements in an array that are not in another

In [ ]:
print(np.setdiff1d(arr1, arr2)) # get values in arr1 that are not in arr2

[1 2]


### compute the elements in either of two arrays, but not both

In [10]:
print(np.setxor1d(arr1, arr2)) # get values that are in either arr1 or arr2 but not in both

[1 2 6 7]
